# pihole_display/config/config.yaml
display:
  backlight:
    pin: 18
    pwm_frequency: 240
    gamma: 1.8
    retry_attempts: 3
  tmux:
    session_name: 'display'
    padd_window: 'padd'
    control_window: 'control'

buttons:
  '1':
    pin: 17
    function: "brightness_system"
    hold_time: 5.0  # Hold for 5 seconds to enter system request
    pull_up: true
    bounce_time: 0.05
  '2':
    pin: 22
    function: "update_select"
    hold_time: 1.0  # Hold for 1 second to enter update request
    pull_up: true
    bounce_time: 0.05
  '3':
    pin: 23
    function: "confirm_1"  # First confirmation option used in system/update request
    hold_time: 0.0
    pull_up: true
    bounce_time: 0.05
  '4':
    pin: 27
    function: "confirm_2"  # Second confirmation option used in system/update request
    hold_time: 0.0
    pull_up: true
    bounce_time: 0.05

logging:
  file: "pihole_display.log"
  level: "INFO"
#  level: "DEBUG"
  max_bytes: 1048576  # Rotate every 1MB
  backup_count: 5 # only keep this many logs

